URL_SERVICE = "https://908df7cf-9a47-4708-affe-bc85de9a9fce.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
